import React, { useEffect, useMemo, useState } from 'react'
import { createPortal } from 'react-dom'
import { ChevronDown, KeyRound, Plus, RefreshCw, Trash2, UserRoundCheck, UserRoundMinus, X } from 'lucide-react'
import api from '../../services/api'
import ConfirmationModal from '../ConfirmationModal'
import toast from 'react-hot-toast'
import Pagination, { usePagination } from '../Pagination'

interface ConnectedClient { clientId: string; employeeName: string | null; employeeId: string | null; recordId: string | null; managerId: string | null; isManager: boolean; managerEmail: string | null }
const emptyCredential = { client: null as ConnectedClient | null, email: '', password: '' }
const primaryButton = 'inline-flex items-center justify-center gap-2 rounded-xl border border-blue-300/30 bg-gradient-to-r from-blue-500 to-sky-500 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-blue-500/20 transition hover:brightness-110 active:scale-[.98] disabled:cursor-not-allowed disabled:opacity-50'
const inputClass = 'mt-2 w-full rounded-xl border border-[var(--border)] bg-[var(--secondary)] px-3 py-2.5 text-[var(--foreground)] outline-none transition placeholder:text-[var(--muted-foreground)] focus:border-[var(--primary)] focus:ring-2 focus:ring-[color-mix(in_oklab,var(--primary)_25%,transparent)]'

const ConnectedClientsTab: React.FC = () => {
  const [clients, setClients] = useState<ConnectedClient[]>([])
  const [loading, setLoading] = useState(true)
  const [credential, setCredential] = useState(emptyCredential)
  const [assignmentFor, setAssignmentFor] = useState<ConnectedClient | null>(null)
  const [assignments, setAssignments] = useState<{ items: any[]; total: number; page: number; limit: number }>({ items: [], total: 0, page: 1, limit: 10 })
  const [selectedClient, setSelectedClient] = useState('')
  const pagination = usePagination(clients, 10)
  const [deleteConfirmation, setDeleteConfirmation] = useState({ isOpen: false, clientId: '', employeeName: '' })

  const fetchClients = async () => { try { setLoading(true); setClients((await api.get('/connected-clients')).data.clients || []) } catch (e: any) { toast.error(e.response?.data?.error || 'Failed to fetch connected clients') } finally { setLoading(false) } }
  useEffect(() => { fetchClients() }, [])
  const loadAssignments = async (manager: ConnectedClient, page = 1) => { try { setAssignments((await api.get(`/connected-clients/${manager.clientId}/manager/assignments`, { params: { page, limit: 10 } })).data) } catch (e: any) { toast.error(e.response?.data?.error || 'Failed to load team') } }
  useEffect(() => { if (assignmentFor) loadAssignments(assignmentFor) }, [assignmentFor?.clientId])
  const available = useMemo(() => clients.filter(c => c.employeeName && !c.isManager && !c.managerId), [clients])
  const saveCredentials = async () => { if (!credential.client) return; try { await api[credential.client.isManager ? 'put' : 'post'](`/connected-clients/${credential.client.clientId}/manager`, { email: credential.email, password: credential.password }); toast.success('Manager credentials saved'); setCredential(emptyCredential); fetchClients() } catch (e: any) { toast.error(e.response?.data?.error || 'Could not save credentials') } }
  const addEmployee = async () => { if (!assignmentFor || !selectedClient) return; try { await api.post(`/connected-clients/${assignmentFor.clientId}/manager/assignments`, { employeeClientId: selectedClient }); setSelectedClient(''); await loadAssignments(assignmentFor); fetchClients(); toast.success('Employee assigned') } catch (e: any) { toast.error(e.response?.data?.error || 'Could not assign employee') } }
  const removeEmployee = async (employeeId: string) => { if (!assignmentFor) return; try { await api.delete(`/connected-clients/${assignmentFor.clientId}/manager/assignments/${employeeId}`); await loadAssignments(assignmentFor, assignments.page); fetchClients(); toast.success('Employee removed') } catch (e: any) { toast.error(e.response?.data?.error || 'Could not remove employee') } }
  if (loading) return <div className="p-8 text-center text-[var(--muted-foreground)]">Loading connected clients...</div>

  return <div className="p-1">
    <div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-bold">Connected Clients</h2><p className="text-sm text-[var(--muted-foreground)]">Create manager logins and assign each manager only their own workforce.</p></div><button onClick={fetchClients} className={primaryButton}><RefreshCw size={16} /> Refresh</button></div>
    <div className="overflow-hidden rounded-xl border border-[var(--border)] bg-[color-mix(in_oklab,var(--card)_80%,transparent)]"><table className="w-full text-sm"><thead className="bg-[var(--secondary)] text-left text-xs uppercase tracking-wider text-[var(--muted-foreground)]"><tr><th className="p-3">Client</th><th className="p-3">Employee</th><th className="p-3">Status</th><th className="p-3 text-right">Actions</th></tr></thead><tbody>{pagination.pageItems.map(c => <tr key={c.clientId} className="border-t border-[var(--border)] transition-colors hover:bg-[var(--accent)]/50"><td className="p-3 font-mono">{c.clientId.slice(0, 8)}...</td><td className="p-3"><b>{c.employeeName || 'Not set'}</b><div className="text-xs text-[var(--muted-foreground)]">{c.employeeId || 'No employee ID'}</div></td><td className="p-3">{c.isManager ? <span className="text-emerald-400">Manager · {c.managerEmail}</span> : c.managerId ? <span className="text-[var(--muted-foreground)]">Assigned to manager</span> : 'Unassigned'}</td><td className="p-3"><div className="flex justify-end gap-2"><button onClick={() => setCredential({ client: c, email: c.managerEmail || '', password: '' })} disabled={!c.employeeName || !!c.managerId} className="inline-flex items-center gap-1.5 rounded-lg border border-blue-400/35 bg-blue-500/15 px-3 py-2 text-xs font-semibold text-blue-200 transition hover:bg-blue-500/25 disabled:cursor-not-allowed disabled:opacity-40">{c.isManager ? <KeyRound size={15} /> : <UserRoundCheck size={15} />}{c.isManager ? 'Edit Credentials' : 'Mark as Manager'}</button>{c.isManager && <button onClick={() => setAssignmentFor(c)} className="inline-flex items-center gap-1.5 rounded-lg border border-[var(--border)] bg-[var(--secondary)] px-3 py-2 text-xs font-semibold transition hover:border-[var(--primary)]"><Plus size={15} /> Team</button>}<button onClick={() => setDeleteConfirmation({ isOpen: true, clientId: c.clientId, employeeName: c.employeeName || c.clientId })} className="rounded-lg border border-red-500/40 bg-red-500/10 p-2 text-red-400 transition hover:bg-red-500/20" title="Delete client"><Trash2 size={16} /></button></div></td></tr>)}</tbody></table><Pagination page={pagination.page} pageSize={pagination.pageSize} totalItems={clients.length} onPageChange={pagination.setPage} onPageSizeChange={pagination.setPageSize} itemLabel="clients" /></div>
    {credential.client && createPortal(<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-2xl border border-blue-300/20 bg-[color-mix(in_oklab,var(--card)_94%,#071222)] p-6 shadow-2xl shadow-blue-950/60"><div className="mb-5 flex justify-between"><div><h3 className="font-bold">{credential.client.isManager ? 'Edit Credentials' : 'Mark as Manager'}</h3><p className="text-sm text-[var(--muted-foreground)]">{credential.client.employeeName}</p></div><button className="rounded-lg p-2 transition hover:bg-[var(--accent)]" onClick={() => setCredential(emptyCredential)}><X /></button></div><label className="block text-sm font-medium">Email<input className={inputClass} placeholder="manager@company.com" type="email" value={credential.email} onChange={e => setCredential(v => ({ ...v, email: e.target.value }))} /></label><label className="mt-4 block text-sm font-medium">{credential.client.isManager ? 'New password (leave blank to keep current)' : 'Password'}<input className={inputClass} placeholder="At least 8 characters" type="password" value={credential.password} onChange={e => setCredential(v => ({ ...v, password: e.target.value }))} /></label><p className="mt-3 text-xs text-[var(--muted-foreground)]">Passwords are securely hashed and cannot be displayed; reset it here when needed.</p><button onClick={saveCredentials} className={`${primaryButton} mt-5 w-full`}>Save credentials</button></div></div>, document.body)}
    {assignmentFor && createPortal(<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm"><div className="w-full max-w-2xl rounded-2xl border border-blue-300/20 bg-[var(--card)] p-6 shadow-2xl"><div className="mb-5 flex justify-between"><div><h3 className="font-bold">{assignmentFor.employeeName}'s workforce</h3><p className="text-sm text-[var(--muted-foreground)]">Only these employees are visible to this manager.</p></div><button className="rounded-lg p-2 hover:bg-[var(--accent)]" onClick={() => setAssignmentFor(null)}><X /></button></div><div className="flex items-end gap-2"><label className="block flex-1 text-sm font-medium">Employee to add<div className="relative mt-2"><select className="w-full appearance-none rounded-xl border border-[var(--border)] bg-[var(--secondary)] px-3 py-2.5 pr-10 text-[var(--foreground)] outline-none transition focus:border-[var(--primary)] focus:ring-2 focus:ring-[color-mix(in_oklab,var(--primary)_25%,transparent)]" value={selectedClient} onChange={e => setSelectedClient(e.target.value)}><option value="">Select an unassigned employee...</option>{available.map(c => <option key={c.clientId} value={c.clientId}>{c.employeeName} ({c.employeeId || c.clientId.slice(0, 8)})</option>)}</select><ChevronDown size={17} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-[var(--primary)]" /></div></label><button className={primaryButton} onClick={addEmployee} disabled={!selectedClient}>Add</button></div><div className="mt-5 divide-y divide-[var(--border)]">{assignments.items.map(e => <div className="flex items-center justify-between py-3" key={e._id}><span>{e.name}</span><button onClick={() => removeEmployee(e._id)} className="text-sm font-semibold text-red-400"><UserRoundMinus className="mr-1 inline" size={15} /> Remove</button></div>)}{assignments.items.length === 0 && <p className="py-5 text-center text-sm text-[var(--muted-foreground)]">No employees assigned yet.</p>}</div></div></div>, document.body)}
    <ConfirmationModal isOpen={deleteConfirmation.isOpen} onClose={() => setDeleteConfirmation({ isOpen:false, clientId:'', employeeName:'' })} onConfirm={async () => { await api.delete(`/connected-clients/${deleteConfirmation.clientId}`); setDeleteConfirmation({ isOpen:false, clientId:'', employeeName:'' }); fetchClients() }} title="Delete Connected Client" message={`Delete ${deleteConfirmation.employeeName} and associated data?`} confirmText="Delete" cancelText="Cancel" type="danger" />
  </div>
}
export default ConnectedClientsTab
